---
title: "Reproducible Research: Peer Assessment 1"
author: "Minjie Xu"
date: "2016年8月19日"
output: html_document:
    keep_md: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Loading and preprocessing the data  

```{r}
activity <- read.csv('activity.csv',na.strings = 'NA',stringsAsFactors = F)
activity$date <- as.Date(activity$date)
activity$interval <- as.factor(activity$interval)
str(activity)
Steps_per_day = tapply(activity$steps,activity$date,sum,na.rm =T,simplify = T)
str(Steps_per_day)
Mean_steps_per_interval = tapply(activity$steps,activity$interval,mean,na.rm=T,simplify = T)
str(Mean_steps_per_interval)
```

##What is mean total number of steps taken per day?  

```{r}
hist(Steps_per_day,breaks = 20,xlab = 'Steps per day',main = 'mean total number of steps taken per day')
mean(Steps_per_day,na.rm = T)
median(Steps_per_day,na.rm = T)
```

##What is the average daily activity pattern?

```{r}
plot(Mean_steps_per_interval,type = 'l',xlab = 'Time',ylab = 'Mean steps per interval',main = 'mean total number of steps taken per interval')
which.max(Mean_steps_per_interval)
```

##Imputing missing values  

strategy using mean steps per day to fill in all of the missing values.

```{r}
sum(is.na(activity$steps))
fill <- activity
for(i in 1:dim(fill)[1]){
  if (is.na(fill[i,1])){
    fill[i,1] = Mean_steps_per_interval[as.character(fill[i,3])]
  }
}
Fill_steps_per_day = tapply(fill$steps,fill$date,sum,simplify = T)
hist(Steps_per_day,breaks = 20,xlab = 'Steps per day',main = 'mean total number of steps taken per day\n NA filled')
mean(Fill_steps_per_day)
median(Fill_steps_per_day)
```


##Are there differences in activity patterns between weekdays and weekends?
```{r}
number <- c()
for(i in 1:dim(fill)[1]){
  t <- weekdays(fill[i,2],T)
  if (t %in% c('周六','周日')){
    number <- c(number,'weekend') 
  } else{
    number <- c(number,'weekday')
  }
}
number <- as.factor(number)
add <- cbind(fill,number)
Bi_mean_steps_per_interval = aggregate(add$steps, list(add$interval,add$number), mean)
library(ggplot2)
g <- ggplot(Bi_mean_steps_per_interval,aes(Group.1,x,group=Group.2))+geom_line()+facet_grid(Group.2~.)
g <- g+ labs(x='Time',y='Mean steps per interval',title= 'mean total number of steps taken per interval')
g <- g+theme(axis.text.x=element_text(angle=90,size = 3))
g
```